# Use an official Maven runtime as a parent image
FROM maven:3.8.1-openjdk-11-slim AS build

# Set the working directory to /app
WORKDIR /app

# Copy the pom.xml file to the working directory
COPY pom.xml .

# Download all dependencies defined in the pom.xml file
RUN mvn dependency:go-offline

# Copy the entire project source code to the working directory
COPY src/ src/

# Build the application using Maven
RUN mvn package

# Use an official OpenJDK runtime as a parent image
FROM openjdk:11-jre-slim

# Set the working directory to /app
WORKDIR /app

RUN useradd -ms /bin/bash apiuser 
USER apiuser

# Copy the executable JAR file from the build stage to the working directory
COPY --chown=apiuser --from=build target/App.jar .

# Set the command to run the application when the container starts
CMD ["java", "-jar", "my-app.jar"]

